# Generated by Django 4.1 on 2022-08-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dakheli', 'dakheli'), ('khareji', 'khareji')], max_length=200, null=True),
        ),
    ]
